### ISSUE TITLE
Changing multiple files should be allowed

### ISSUE THREAD

**Issue by axic** [ethereum/EIP-Bot#10]
The old bot allowed changing multiple EIPs in one PR as long as all relevant authors agreed.

There are cases where updating connected EIPs atomically is very beneficial.

**Comment by alita-moore** [comment]
this is a repeat of https://github.com/alita-moore/PM/issues/4 I will bump its priority

**Comment by alita-moore** [comment]
this is added by https://github.com/ethereum/EIP-Bot/compare/b6cf981087e888b5d7fbd4726458c453f8491532...310fd6cead3459789b27043539886d929fd2930e
