### ISSUE TITLE
Close some issues

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIP-Bot#104]
Specifically, the linting issues.

Those are being handled by https://github.com/ethereum/eipw

**Comment by Pandapip1** [comment]
https://github.com/ethereum/EIP-Bot/issues/98
https://github.com/ethereum/EIP-Bot/issues/96
https://github.com/ethereum/EIP-Bot/issues/93
https://github.com/ethereum/EIP-Bot/issues/74
https://github.com/ethereum/EIP-Bot/issues/73
https://github.com/ethereum/EIP-Bot/issues/72
https://github.com/ethereum/EIP-Bot/issues/71
https://github.com/ethereum/EIP-Bot/issues/70
https://github.com/ethereum/EIP-Bot/issues/69
https://github.com/ethereum/EIP-Bot/issues/68

**Comment by Pandapip1** [comment]
CC @MicahZoltu

**Comment by MicahZoltu** [comment]
It is probably better to comment on each of the respective issues, rather than collating them here.  It makes it harder to track/manage and discuss when there is a monolithic list like this.

Are you sure EIPW handles #93?  I thought we still had a problem with that?

**Comment by MicahZoltu** [comment]
Same question for #74 and #69, are we sure the bot handles these?  For #69 I thought we were still actively debating what the behavior should be and the bot doesn't do anything about them at the moment?

**Comment by Pandapip1** [comment]
> Are you sure EIPW handles https://github.com/ethereum/EIP-Bot/issues/93? I thought we still had a problem with that?

> Same question for https://github.com/ethereum/EIP-Bot/issues/74 and https://github.com/ethereum/EIP-Bot/issues/69, are we sure the bot handles these?

There are open issues on the eipw repo. This place is no longer the right place to track this.

**Comment by MicahZoltu** [comment]
I don't see a replication of #93 on EIPW issues list, do you happen to know which number it is?

I guess #74 is handled by the more general "no external links allowed" lint that we currently have.

I also don't see an issue duplicating #69 in the EIPW repository.

**Comment by Pandapip1** [comment]
Issues made.
