### ISSUE TITLE
[bug] Stagnant bot isn't listing authors in original message.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/EIP-Bot#12]
https://github.com/ethereum/EIPs/pull/3847#issue-727319652

Note that the `authors: ` and `EIP Editors: ` lines are empty.

**Comment by alita-moore** [comment]
fixed by https://github.com/ethereum/EIP-Bot/commit/519c91e2b8039fc6660640b8fef8e8e88b37c0ba
