### ISSUE TITLE
Delete old branches

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIP-Bot#121]
- [x] `manual-bot-rerun`: Previously used to re-run EIP-Bot. Now handled by a different system.
- [x] `rerun-pull-request-target-on-review`: Previously used to re-run EIP-Bot. Now handled by a different system.

@alita-moore could you give some guidance on what all the other branches are and if it's safe to delete them?

**Comment by alita-moore** [comment]
Don't delete delete-failed-on-review it's for the marking stale bot

**Comment by alita-moore** [comment]
Also mark-eips-stale

**Comment by alita-moore** [comment]
Should be good to clear everything else, but verify the bots being used on EIPs
