### ISSUE TITLE
Stagnant bot shouldn't mention EIP Editors.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/EIP-Bot#13]
The EIP Editors don't need to take any action when the bot alerts of a stagnant EIP.  The authors need to be notified so they can override but the editors don't have any action to take so they shouldn't be mentioned.

**Comment by MicahZoltu** [comment]
The issue here is that the merge bot is piping up on the stagnant EIPs.  Ideally it would skip over those.

**Comment by lightclient** [comment]
It also seems like it require editor approval too? This should auto merge after some grace period I think.

**Comment by poojaranjan** [comment]
I am blanking if a grace period is already decided, if not, it could be up to 2 weeks (inspired by the "Last Call").

It would be nice to have the message delivered in the original message to the author that the EIP author has 2 weeks time to resuscitate the proposal.

![image](https://user-images.githubusercontent.com/29681685/132406947-a0a79e81-8865-499f-800d-56a5d1ab94df.png)

**Comment by alita-moore** [comment]
editors are removed by https://github.com/ethereum/EIP-Bot/commit/92f5c1123248a69ea223769cdfef20c2030c3f33

what's the consensus on grace period? cc @MicahZoltu @lightclient @poojaranjan

**Comment by MicahZoltu** [comment]
Two weeks is fine with me.

**Comment by alita-moore** [comment]
ok, that behavior is defined here: https://github.com/ethereum/EIP-Bot/commit/6ca2786b59aff50d83d7060f713af161941c7614
