### ISSUE TITLE
[Improvement suggestion] PR title created by bot 

### ISSUE THREAD

**Issue by poojaranjan** [ethereum/EIP-Bot#14]
For the title of the PRs created by bot, it would be nice to have "-" between EIP & the number. 
eg [ #3847](https://github.com/ethereum/EIPs/pull/3847)
![image](https://user-images.githubusercontent.com/29681685/132409070-fc41da31-e166-4802-90a8-9297e01255fe.png)

could be 
EIP-1444 stagnant (2021-Sep-5th@01.10.32) 

I imagine the bot using "EIP-123"  would help people follow how to better refer to an EIP.

**Comment by alita-moore** [comment]
fixed by https://github.com/ethereum/EIP-Bot/commit/6e38082fb659d559a6190943dd8cbb5ebeeaecf7
