### ISSUE TITLE
[feature] Author should be able to move an EIP to Withdrawn.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/EIP-Bot#16]
https://github.com/ethereum/EIPs/pull/4189/checks?check_run_id=3644780168

This EIP was moved to Withdrawn by the author, but it is being blocked on editor review.  An author should be able to move an EIP to Withdrawn at any time, without any editor review.

**Comment by alita-moore** [comment]
this addressed by https://github.com/ethereum/EIP-Bot/commit/df5b0b38ad8dc454678e2ba022e93230b59c256c
