### ISSUE TITLE
[feature] bot should not open a PR for EIPs with active pull requests against them (non-bot generated)

### ISSUE THREAD

**Issue by alita-moore** [ethereum/EIP-Bot#17]
cc @micahzoltu if you have anything to add here

**Comment by MicahZoltu** [comment]
Description looks good.  The goal is to make it so if someone *is* working on an EIP it will not be marked as stagnant.  We can deal with stale PRs separately (maybe manual).

**Comment by alita-moore** [comment]
I think stale PRs are already handled

**Comment by alita-moore** [comment]
addressed by https://github.com/ethereum/EIP-Bot/compare/6ca2786b59aff50d83d7060f713af161941c7614...3f3b9700199b2d6991ce988b73a9b3da3384b98a

**Comment by xinbenlv** [comment]
Thanks for continue to improve EIPbot, this is great improvement
