### ISSUE TITLE
[feature] Automerge withdrawn EIPs

### ISSUE THREAD

**Issue by lightclient** [ethereum/EIP-Bot#18]
Intuitively, it feels like if the author of an EIP elects to withdraw the EIP, it shouldn't need editor approval.

See here for example:
https://github.com/ethereum/EIPs/pull/4189

**Comment by alita-moore** [comment]
cc @micahzoltu

**Comment by MicahZoltu** [comment]
Yes.  If an author approves a withdraw, it should auto-merge.  I think it should *also* auto-merge if an editor approves, that way if we receive approval in an incorrect form (like an author just giving a thumbs up or a PR comment) we can push things through for them without having to override.

**Comment by alita-moore** [comment]
btw I won't add this until it's a [feature] / concensus

**Comment by MicahZoltu** [comment]
There isn't likely to be anyone else who chimes in on the issue.  @pooja may have some thoughts, but none of the other editors actively participate in these kinds of discussions.

**Comment by alita-moore** [comment]
This will also be accomplished via https://github.com/ethereum/EIP-Bot/commit/df5b0b38ad8dc454678e2ba022e93230b59c256c
