### ISSUE TITLE
[bug] Mentions inside code blocks don't work.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/EIP-Bot#19]
Currently, the bot puts editor mentions inside a code block.  However, these mentions don't actually mention people.  See:
https://github.com/ethereum/EIPs/pull/4188#issuecomment-922466675

**Comment by alita-moore** [comment]
this was changed recently; it's no loner relevant [e.g.](https://github.com/ethereum/EIPs/pull/3773#issuecomment-920852215)
