### ISSUE TITLE
[feature] changes to final PRs should first mention authors, then editors after author approval.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/EIP-Bot#20]
When someone submits a PR to change a final EIP, the bot should first @mention the authors.  Once the author has approved the PR (or if the PR author is an author on the EIP) it should then @mention the editors for review.

Right now it appears to skip straight to mentioning the editors, and does not attempt to contact the authors at all.

**Comment by alita-moore** [comment]
Is this only for final PRs or is it okay to implement this for everything? Might be easier that way

**Comment by MicahZoltu** [comment]
For changes to non-final EIPs that don't touch the status field, once the author approves the PR is automerged, no editor involvement.  For changes that change the status or touch a final EIP, it should get author approval first (if the PR author isn't on the EIP authors list), and then after it is author approved it would prompt for editor approval.

**Comment by alita-moore** [comment]
mainly I'm just referring to any case that prompts for editor, should it do it in a step-by-step manner like you mentioned?

**Comment by MicahZoltu** [comment]
> mainly I'm just referring to any case that prompts for editor, should it do it in a step-by-step manner like you mentioned?

Ideally, yes.  No point in getting editors involved prior to getting the necessary author approvals.

**Comment by alita-moore** [comment]
this is accomplished via https://github.com/ethereum/EIP-Bot/commit/4c2fb48b5ae73c2f521d024fa1fc6f5bc7457f15
