### ISSUE TITLE
[feature] Add labels to PRs

### ISSUE THREAD

**Issue by poojaranjan** [ethereum/EIP-Bot#28]
Add feature to eip-bot 
- New EIP: PR for adding a new file under ./eips 
- Status Change: PR that only changes the status
- Update EIP: PR for updating the contents of an EIP, not meant for status changes

**Comment by alita-moore** [comment]
this feature has been added via https://github.com/ethereum/EIP-Bot/pull/39

**Comment by alita-moore** [comment]
follow up bugs or feature extensions will be addressed in separate issues
