### ISSUE TITLE
[bug] job fails critical exception no message (actually file format error)

### ISSUE THREAD

**Issue by alita-moore** [ethereum/EIP-Bot#30]
This is a ticket to follow up on https://github.com/ethereum/EIPs/pull/4393#issuecomment-982227971

**Comment by Andrel2s** [comment]
Jump

**Comment by alita-moore** [comment]
Also occurs here https://github.com/ethereum/EIPs/pull/4511#issuecomment-983142744

**Comment by alita-moore** [comment]
i fixed this, but need to add tests and fix the reason tests missed it

**Comment by alita-moore** [comment]
this was completed by https://github.com/ethereum/EIP-Bot/commit/55f81c606e2cdb077ecccdc2eab47e15b9545b37
