### ISSUE TITLE
Welcome bot has \n\n in text rather than newlines.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/EIP-Bot#31]
What welcome bot says:
> Since this is your first issue, we kindly remind you to check out EIP-1 for guidance.\n\nIf this issue was created as a “discussions-to” for an EIP or to discuss an idea for an EIP, please close it and create a thread at Fellowship of Ethereum Magicians.

What welcome bot should say:
> Since this is your first issue, we kindly remind you to check out EIP-1 for guidance.
> 
> If this issue was created as a “discussions-to” for an EIP or to discuss an idea for an EIP, please close it and create a thread at Fellowship of Ethereum Magicians.

https://github.com/ethereum/EIPs/issues/4509#issuecomment-982338663

**Comment by mryalamanchi** [comment]
@alita-moore The same "\n\n" will show up in the github-actions comment when a first PR is made.
I found the issue. Making a PR to fix this explanation!

**Comment by mryalamanchi** [comment]
So, the changes are to be done in the [EIPs/.github/workflows/greetings.yml](https://github.com/ethereum/EIPs/tree/master/.github/workflows/greetings.yml).
But the PR template doesn't address making changes to the workflows folder.

What do you suggest I do @alita-moore?

**Comment by alita-moore** [comment]
Thank you! Cc me in that pr and I'll review

**Comment by mryalamanchi** [comment]
On it!

**Comment by alita-moore** [comment]
I think you can just make the change and submit it and I can override if the change is fine

**Comment by alita-moore** [comment]
Thank you so much! This issue is closed https://github.com/ethereum/EIPs/pull/4517

**Comment by mryalamanchi** [comment]
That was super quic!
Let me pick few more over weekend.
