### ISSUE TITLE
[bug] bot not re-running properly

### ISSUE THREAD

**Issue by alita-moore** [ethereum/EIP-Bot#32]
https://github.com/ethereum/EIPs/pull/4507#issuecomment-981692647

**Comment by alita-moore** [comment]
https://github.com/ethereum/EIPs/pull/4495#issuecomment-986426421

**Comment by mryalamanchi** [comment]
@alita-moore, I am unsure what's the exact issue. Can you post a summary?

**Comment by alita-moore** [comment]
> [ethereum/EIPs#4495 (comment)](https://github.com/ethereum/EIPs/pull/4495#issuecomment-986426421)

this one is actually the same as this issue: https://github.com/ethereum/EIP-Bot/issues/35 which is nearly fixed

**Comment by alita-moore** [comment]
> [ethereum/EIPs#4507 (comment)](https://github.com/ethereum/EIPs/pull/4507#issuecomment-981692647)

as you can see here: https://github.com/ethereum/EIPs/actions/runs/1514005891/attempts/1

there were 3 attempts, with 2 runs for re-run. After the first re-run the bot passed but the `enable-auto-merge` failed and same the third. So I think it's reasonable to conclude that the problem is not the re-run bot but instead the lack of `enable-auto-merge` passing

so this one is also the same as this issue: #35 which is nearly fixed

**Comment by alita-moore** [comment]
Closing this because both reported problems are the same problem as #35
