### ISSUE TITLE
[bug] No autogenerated message displayed for new Issue

### ISSUE THREAD

**Issue by poojaranjan** [ethereum/EIP-Bot#33]
Based on earlier addition to bot's functionality, the general expectation is that for a new Issue, bot should display a message for the user to ensure the issue created is not for the "discussion-to".

Unfortunately, I don't see any such message for the [Issue 4500](https://github.com/ethereum/EIPs/issues/4500)

![Screen Shot 2021-11-30 at 10 46 40 AM](https://user-images.githubusercontent.com/29681685/144080106-c8be6e0d-0855-4a65-abe5-81e62d9f743a.png)

Someone might want to look into it.

**Comment by poojaranjan** [comment]
I was assuming that the "bot-message" is displayed for every new issues but recently learned that is only for new users. 

It would be nice to have the bot-message for every new issue, at least for a period of time until we streamline the process. 

Bot message - _Since this is your first issue, we kindly remind you to check out EIP-1 for guidance. If this issue was created as a “discussions-to” for an EIP or to discuss an idea for an EIP, please close it and create a thread at Fellowship of Ethereum Magicians_.

**Comment by MicahZoltu** [comment]
If we switch to having the bot comment on *every* new issue then we should remove the bit at the start that says "Since this is your first issue, ".
> If this issue was created as a “discussions-to” for an EIP or to discuss an idea for an EIP, please close it and create a thread at [Fellowship of Ethereum Magicians](https://ethereum-magicians.org/).

**Comment by alita-moore** [comment]
@MicahZoltu @poojaranjan what do you all feel is the best next step here?

**Comment by MicahZoltu** [comment]
I *think* we decided in the meeting that the bot should comment on every issue.  If it does, I still recommend the text in my previous comment.  Does anyone remember if this was decided or not? @poojaranjan @lightclient?

**Comment by alita-moore** [comment]
Okay, I'll add it. It will be easy to change if it's not desirable

**Comment by poojaranjan** [comment]
I am fine with suggested changes by @MicahZoltu. I think it make sense to remove the first issue statement.

**Comment by poojaranjan** [comment]
>Does anyone remember if this was decided or not? 

I have to revisit the decision, but I suppose adding the comment to every new issue created, will help users to read and follow.

**Comment by mryalamanchi** [comment]
Yes, the bot-comment should be added to every issue, be it from a `first-time-issue-creator` or users who already created it before. 

The eip-1, itself, can go under updates that both might not be aware of.
Suggestion for bot-message:
> We kindly remind you to check out EIP-1 for guidance.
>
> If this issue was created as a “discussions-to” for an EIP or to discuss an idea for an EIP, please close it and create a thread at Fellowship of Ethereum Magicians.

Also, should we provide the link to Fellowship of Ethereum Magicians?

**Comment by MicahZoltu** [comment]
Yes, the Ethereum magicians reference should be a link.

**Comment by alita-moore** [comment]
This was implemented via https://github.com/ethereum/EIPs/commit/4031ae6321217d17df3748ac1df43f4a5377b7ba
