### ISSUE TITLE
[bug] (EIPs repo) only run on canonical branch

### ISSUE THREAD

**Issue by alita-moore** [ethereum/EIP-Bot#37]
https://github.com/ethereum/EIPs/issues/4526

**Comment by alita-moore** [comment]
fixed via https://github.com/ethereum/EIPs/commit/627685c6e670a6afe48add2878fb68f1f2482075 thanks to @mryalamanchi 

Thank you @mryalamanchi 🥳

**Comment by mryalamanchi** [comment]
Getting a hang of it @alita-moore 😂
More to come 🤙🏻
