### ISSUE TITLE
EIP merged but unavailable at eips.ethereum.org

### ISSUE THREAD

**Issue by poojaranjan** [ethereum/EIP-Bot#40]
PR - [4393](https://github.com/ethereum/EIPs/pull/4393) is merged to create a new EIP in `Draft`.
![image](https://user-images.githubusercontent.com/29681685/147839074-d309bd7b-1524-48f0-a711-34950f8d38e5.png)

But I am unable to find the EIP
![image](https://user-images.githubusercontent.com/29681685/147839078-b06854a2-d12b-4936-ac8b-0b92ba23ce43.png)

Can someone please look into the issue? Thanks!

**Comment by MicahZoltu** [comment]
Known issue, @mryalamanchi said they were going to fix it in https://github.com/ethereum/EIPs/issues/4614#issue-1090395253

**Comment by mryalamanchi** [comment]
I am on it!

**Comment by mryalamanchi** [comment]
Done!
PR created: <https://github.com/ethereum/EIPs/pull/4619>
