### ISSUE TITLE
[bug] Greeter should only greet on issues.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/EIP-Bot#44]
The greeter that tells everyone who creates an issue and a pull request to move to ethereum magicians.  It should only do this for issues.

**Comment by alita-moore** [comment]
I removed the comment on PRs: https://github.com/ethereum/EIPs/commit/a192c2bc90bf198d86bc14bcddfd09b321c69aa8

note that this removes greetings from ALL PRs, which differs from the original behavior of a first-time bot mention on PR or issues. This is trivial to fix, if you'd like to revert the behavior so I'm marking this as complete for now
