### ISSUE TITLE
Run bot on review state change

### ISSUE THREAD

**Issue by alita-moore** [ethereum/EIP-Bot#48]
https://github.com/ethereum/EIPs/pull/4835

**Comment by alita-moore** [comment]
https://github.com/ethereum/EIPs/pull/4835#issuecomment-1048458635

**Comment by alita-moore** [comment]
this should already be happening so the fact it's not suggests something else

**Comment by alita-moore** [comment]
so the last run was at 11:18 my time but then the author marked their PR for review at 11:19
<img width="889" alt="Screen Shot 2022-02-22 at 11 28 40 PM" src="https://user-images.githubusercontent.com/26529820/155266183-e540f39e-b591-4c58-b97e-aac499d4696f.png">
<img width="733" alt="Screen Shot 2022-02-22 at 11 29 30 PM" src="https://user-images.githubusercontent.com/26529820/155266242-8107b980-345b-41fa-9a8a-f8bdc3b76ada.png">

So most likely, the action wasn't called. I also verified this behavior here:
https://github.com/ethereum/EIPs/pull/4840

You'll see that when I open for review the auto merge bot remains skipped

**Comment by alita-moore** [comment]
Which, means that the `activity types` described in the `pull_request_target` is incorrect. And that `pull_request_target` is not called on `ready_for_review`

**Comment by alita-moore** [comment]
I submitted a support ticket for this topic because it appears to be on github's side (see above)
link, you probably can't access but just in case.. https://support.github.com/ticket/personal/0/1514149

**Comment by Pandapip1** [comment]
See also #4833, I think the bot just failed to run for an hour.

**Comment by alita-moore** [comment]
that's an interesting idea..

**Comment by Pandapip1** [comment]
Might be possible with https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment (and then check if the message contains @eth-bot?)

**Comment by Pandapip1** [comment]
Hopefully https://github.com/ethereum/EIPs/pull/4922 should provide enough info.

**Comment by Pandapip1** [comment]
Closing this as it appears to be a GitHub bug.
