### ISSUE TITLE
[feature] Bot should allow non-EIP changes

### ISSUE THREAD

**Issue by lightclient** [ethereum/EIP-Bot#5]
After 1 editor approval, the bot should allow non-EIP changes like to the pages infra. See this PR as an example: https://github.com/ethereum/EIPs/pull/3581

**Comment by alita-moore** [comment]
This is accomplished by https://github.com/ethereum/EIP-Bot/commit/b9e93303069edea7875281e9b5cb52b483ecd3e6

This implements a few features:
- eip authors can also make changes to the assets file which will allow any changes so long as the eip passes; i.e. I can do whatever I want to assets/eip-2/.. if I (at the same time) make changes to EIPs/eip-2.md and that is eligible for auto-merge.
- if an editor approves then any non eip file will pass

I also made a few cleanups
- better error handling
- cleaner code
- more tests
- conitnuing transition to class based approach (I'm converting old style to new style whenever I make changes to that file
