### ISSUE TITLE
EIP Bot fails when adding Git Submodule

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIP-Bot#56]
See: https://github.com/ethereum/EIPs/issues/4921 and https://github.com/ethereum/EIPs/pull/4835

**Comment by Pandapip1** [comment]
More info:
![image](https://user-images.githubusercontent.com/45835846/158585670-885bce57-c1a0-4e46-a4c7-c7aa74470a13.png)
![image](https://user-images.githubusercontent.com/45835846/158585579-13e95581-6667-4193-98ac-9ad3dbbdaa7f.png)

**Comment by Pandapip1** [comment]
cc @alita-moore @mryalamanchi

**Comment by MicahZoltu** [comment]
As per my comment in https://github.com/ethereum/EIPs/issues/4921, I think the current bot behavior is correct.  Authors shouldn't be adding git submodules to the EIPs repository.

**Comment by Pandapip1** [comment]
Closed - see https://github.com/ethereum-cat-herders/EIPIP/issues/116
