### ISSUE TITLE
[enhancement, priority low] Automatically Managed CODEOWNERS file

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIP-Bot#58]
I suggest that the EIP bot automatically add the EIP editors to the codeowners file for new EIP files (so that a review from the CODEOWNERS is required). Then, once it is merged, the CODEOWNERS file could change to the EIP authors (so that a review from the authors is required). The bot could still fail on status change (e.g. Review -> Final), so that the EIP editors AND the EIP authors have to approve it. The nice thing about this is that the EIP editors or the EIP authors are immediately requested for review.

**Comment by MicahZoltu** [comment]
I didn't know about the CODEOWNERS file, this is interesting and maybe could simplify some of our automation.  I would be curious to hear @alita-moore's thoughts on whether something like this would cause problems or not.

**Comment by alita-moore** [comment]
Ya that's a good idea if we can get EIP level resolution for code owners. I've only seen repo wide code owners. But it would simplify the code.

To be clear, though. This is perfectly possible with the bot as is. And it would be faster to just automatically request authors on the PR from the code itself.

**Comment by MicahZoltu** [comment]
The CODEOWNERS file supports per-file codeowners, as well as per-directory.  When an EIP is created we could automatically add `assets/eip-####/` and `EIPS/eip-####.md` to the list.  We would probably want to wait until it was merged though, as EIP number isn't final until then.

**Comment by JEAlfonsoP** [comment]
Hi you all.
I would like to use some references in order to approach this issue (https://github.com/ethereum/EIP-Bot/issues/58)


EIP 1 defined EIP editors (current and emeritus) responsibilities: ie, assign Last Call status and notify authors for next steps during the process.

In the other side: (GitHub Docs)
Code owners are automatically requested for review when someone opens a pull request that modifies code that they own..

From above we would infer that EIP Linting Bot as it is notifies the relevant individuals for review, and merges simple changes automatically.

**Comment by JEAlfonsoP** [comment]
cc @Pandapip1 Hi mate, could we close this issue if there is no any additional pending action ?

**Comment by Pandapip1** [comment]
Well, there is a pending action. Just not a high-priority one like some of the others.

**Comment by JEAlfonsoP** [comment]
Hi,  in order to be in the same page could you please specify me the pending action. I may be confused. Ty

**Comment by Pandapip1** [comment]
The pending action is to have the EIP-bot automatically populate a CODEOWNERS file.

**Comment by JEAlfonsoP** [comment]
This issue was mentioned during the last call but has not been decided if it would be implemented or not..

**Comment by Pandapip1** [comment]
I think that it probably will be implemented (there are no objections), once there is a PR that implements it.

It's nice not having "checks on your PR failed" emails sent every time you push a commit.

**Comment by Pandapip1** [comment]
This won't work. All CODEOWNERS entries need to have write permission.
