### ISSUE TITLE
Master branch may be renamed to main

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIP-Bot#60]
See: https://github.com/ethereum/EIPs/issues/4945

This is to discuss if there may be eth-bot-related issues with this potential change, and if so, how much time it would take to fix any identified problems.

**Comment by alita-moore** [comment]
shouldn't be, no, but need to update repo rules where applicable

**Comment by JEAlfonsoP** [comment]
cc @MicahZoltu Hi, I think this was agreed during the last EIPIP call that the renaming would not be implemented. Please if this is the case could we close this issue ?

**Comment by Pandapip1** [comment]
Actually, the issue is still very much active. Since there are no problems with the renaming from a technical perspective, however, this can be closed.
