### ISSUE TITLE
Automatically update/insert fields immediately before merging EIP pull requests

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIP-Bot#61]
These haven't been discussed and I'm mostly posting them here for discussion and tracking purposes. Don't start implementing yet!

That said, it would be pretty sweet if one of the EIP bots could handle making a commit setting some values on behalf of editors/authors.

 - [ ] Setting the EIP number `[PROPOSED]`
 - [ ] Setting the `created` date `[PROPOSED]`
 - [ ] Setting the `last-call-deadline` date to 14 days after merging `[PROPOSED]`

**Comment by JEAlfonsoP** [comment]
This issue is basically covered in issue 55, Pandapip1 list..

I propose to close one of the two.

**Comment by SamWilsn** [comment]
That's my bad! closing in favour of #55
