### ISSUE TITLE
Disallow EIP-* in the preamble `title` and `description` fields

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIP-Bot#67]
_Originally from #55_

At minimum, it would be nice if the bot failed CI if it found text matching `eip[-\s]*[0-9]+` or `erc[-\s]*[0-9]+` in the `title` and `description` preamble fields.

A further step would be to either comment on the PR, or automatically apply the suggestion to the PR.

Personally I would prefer a comment on the PR, but we should probably discuss in this issue.

**Comment by JEAlfonsoP** [comment]
I will work on it.

**Comment by SamWilsn** [comment]
Small tweak: instead of banning all EIPs in the title/description, only ban the current EIP.

See ethereum/EIPs#5008 for an example of why we should allow other EIPs in those fields.

**Comment by SamWilsn** [comment]
Covered in eipw.
