### ISSUE TITLE
Require that all mandatory preamble headers are present and in the correct order

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIP-Bot#68]
_Originally from #55_

At minimum, it would be nice if the bot failed CI if the preamble fields are out of order or missing (I think it does some amount of this already.)

A further step would be to either comment on the PR, or automatically apply the suggestion to the PR.

Personally I would prefer a comment on the PR, but we should probably discuss in this issue.

**Comment by JEAlfonsoP** [comment]
I will work on it.

**Comment by JEAlfonsoP** [comment]
Issue 71

**Comment by JEAlfonsoP** [comment]
@SamWilsn could you please confirm this issue is cover with Issue 71. 
https://github.com/ethereum/EIP-Bot/issues/71

If that so, Could we please close this issue and focus only in issue 71.?
Thanks.

**Comment by SamWilsn** [comment]
I believe that #71 is for section headers (`## Abstract`, `## Specification`, etc.) while this issue is for the preamble fields (`requires:`, `title:`, and so on.)

**Comment by JEAlfonsoP** [comment]
Ok. I will deal this separately.

**Comment by MicahZoltu** [comment]
This is handled by EIPW now.
