### ISSUE TITLE
[feature] Mention different editors for different types of EIPs

### ISSUE THREAD

**Issue by alita-moore** [ethereum/EIP-Bot#7]
as mentioned by @MicahZoltu it would be good to mention different sets of editors based on what the type of eip is being considered.

**Comment by alita-moore** [comment]
@micahzoltu do you want to do this hardcoded or is there a way to determine what kind of eip it is automatically?

**Comment by MicahZoltu** [comment]
The EIP metadata has the EIP type in it.  Core, Networking, Interface, etc.  Which editors pay attention to which EIP types will have to be hard coded somewhere, similar to the list of EIP editors (maybe the same list, but with additional per-editor data).

**Comment by alita-moore** [comment]
What is / where can I find the relevant people per type?

**Comment by MicahZoltu** [comment]
This is an excellent question.  At the least, Micah on Core EIPs and Lightclient on ERCs.  I'm not sure how to distribute the rest.

**Comment by alita-moore** [comment]
I'll just default others to all

**Comment by hamedalex1** [comment]
عدعتحدرنرنزتلاباعیهبهزن۶بتخعب

**Comment by alita-moore** [comment]
@MicahZoltu I'm doing this today, are there any developments on procuring a list of appropriate people to mention? Also, if it's helpful I can implement this as an input for the bot so it's easier to change

**Comment by MicahZoltu** [comment]
It would be nice to have it be an input that can be configured easily without having to publish a new version of the bot.

Perhaps the initial implementation can just put all of the editors on everything except for me, and have everyone including me on the Core EIPs category.  If configuration is easy then people can just submit a PR to remove themselves from one or both lists if they want.

**Comment by alita-moore** [comment]
Okay, I'll do that

**Comment by alita-moore** [comment]
This is completed by https://github.com/ethereum/EIP-Bot/compare/310fd6cead3459789b27043539886d929fd2930e...950d79ddd687f4c78bca2ae49c234d7ebfce0d1f

to change the editors you just have to edit the auto-merge-bot.yml with new names https://github.com/ethereum/EIPs/blob/master/.github/workflows/auto-merge-bot.yml
