### ISSUE TITLE
Require CC0 waiver

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIP-Bot#70]
_Originally from #55_

At minimum, it would be nice if the bot failed CI if an EIP does not contain the CC0 waiver.

A further step would be to either comment on the PR, or automatically apply the suggestion to the PR.

Personally I would prefer a comment on the PR, but we should probably discuss in this issue.

**Comment by JEAlfonsoP** [comment]
I will work on it.

**Comment by Pandapip1** [comment]
Note: ethereum/EIPs#5055

**Comment by JEAlfonsoP** [comment]
So bot must failed if no CC0 waiver ? (Direct Question)

**Comment by MicahZoltu** [comment]
Yes, if a new EIP doesn't have the exactly correct license section then the bot should hard fail.  Even better, it would comment on the PR indicating what needs to be changed/fixed.

**Comment by JEAlfonsoP** [comment]
Is it a possibility just before merge, to check if license is null, warn and update license = CC0 ? 
Let me know if you agree with it.

**Comment by Pandapip1** [comment]
Well, IIUC the user needs to agree to it (see metamask's CLA bot)

**Comment by MicahZoltu** [comment]
This is handled by EIPW now.

**Comment by SamWilsn** [comment]
> This is handled by EIPW now.

It isn't, but I have an issue open for it: ethereum/eipw#27. It should be pretty easy to implement as an `eipw` lint.
