### ISSUE TITLE
Require mandatory EIP sections and disallow others

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIP-Bot#71]
_Originally from #55_

At minimum, it would be nice if the bot failed CI if an EIP didn't contain all the required top level sections as defined in EIP-1, or if it contains top level sections that aren't defined in EIP-1.

A further step would be to either comment on the PR, or automatically apply the suggestion to the PR.

Personally I would prefer a comment on the PR, but we should probably discuss in this issue.

**Comment by JEAlfonsoP** [comment]
I will work on it.

**Comment by JEAlfonsoP** [comment]
please confirm this is the consensus: so EIP-BOT will fail if EIP does not contain all the required top level sections as defined in EIP-1, or if it contains top level sections that aren't defined in EIP-1.

**Comment by MicahZoltu** [comment]
That is correct @JEAlfonsoP.

**Comment by MicahZoltu** [comment]
This is handled by EIPW now.
