### ISSUE TITLE
Download and render external links as PDFs

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/EIP-Bot#75]
This issue should probably be split into many issues with different priorities.

I disagree. Making PDFs of web pages might still be useful.

I suggest the following:
1. All external links are converted to PDFs.
1. All the PDFs are put in a new folder, `assets/references`.
1. The links are changed to IPFS multihashes.
1. The Ethereum foundation runs an IPFS node that pins these files.

I'll make this a new issue in the EIP repository.

_Originally posted by @Pandapip1 in https://github.com/ethereum/EIP-Bot/issues/55#issuecomment-1103834429_

**Comment by SamWilsn** [comment]
I am against mirroring pages _automatically_ as PDFs in the EIPs repository. It's super complex, opens up a ton of possible attack vectors, and will take a _ton_ of space. Not to mention that git doesn't handle binaries super well, and the crazy copyright considerations.

I would not be against a tool to mirror a webpage in a compatible way that an author could use to include an external reference. I just don't think it should be automatic.

**Comment by JEAlfonsoP** [comment]
I would suggest to discuss this issue during the next call..

**Comment by Pandapip1** [comment]
Since we're not allowing external links, I think we can close this.
