### ISSUE TITLE
Updating workflow files should use stricter rules

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIP-Bot#79]
See https://github.com/ethereum/EIPs/pull/4859

Multiple editors should be required to add/remove editors or manage other parts of the EIP Bot.

Currently, any EIP editor can remove all other EIP editors and/or add any user as an editor - this appears to be a pretty serious security flaw.

**Comment by JEAlfonsoP** [comment]
Question: how does the bot could avoid editors re-writing any part of the bot's code ?

**Comment by MicahZoltu** [comment]
I actually don't *think* the bot will automerge changes to `/.github/*`.  If it does, we should fix that.  I *believe* I manually merged that commit, not the bot.  I am able to do that because I'm an admin of this repository, and there is essentially nothing the bot can do about a rogue admin.

**Comment by JEAlfonsoP** [comment]
Ok, thanks. Could we close this issue ?

**Comment by Pandapip1** [comment]
It really looks like the bot was about to auto-merge it (but then you enabled auto-merge first): https://github.com/ethereum/EIPs/pull/4859#issuecomment-1054459875

**Comment by JEAlfonsoP** [comment]
Who merged it ? bot or editor ?

**Comment by MicahZoltu** [comment]
Enabling auto-merge I believe happens automatically, but it still needs other checks to pass before it will auto-merge?  I think one of the other checks would have failed?

**Comment by Pandapip1** [comment]
Nope. The auto merge action is usually skipped. This is what it looked like before the approval:
![image](https://user-images.githubusercontent.com/45835846/166957421-9f45c222-6a73-4e40-bb6f-03c9955ef278.png)
After the approval:
![image](https://user-images.githubusercontent.com/45835846/166957479-cd519c68-17ae-44b9-af1f-b7acbadcfe06.png)
Clearly, the EIP bot passed all checks, and so the auto merge action wasn't skipped.

ethereum/EIPs#5073 will give us all the information we need, once an editor approves it.

**Comment by Pandapip1** [comment]
Here's another screenshot from the before/after logs:

![image](https://user-images.githubusercontent.com/45835846/166958286-1045f429-0f4b-4a50-8a99-43f3d979f711.png)
![image](https://user-images.githubusercontent.com/45835846/166958161-0874595b-849a-4499-b088-36d17795c83a.png)

**Comment by MicahZoltu** [comment]
@Pandapip1's experiment was a success, and this is in fact a problem.  Essentially anything that isn't an EIP should require multiple editor approvals to merge.  We should probably have one set of rules for this and just apply it globally, rather than doing it per file/filetype.

**Comment by JEAlfonsoP** [comment]
let me know if this is the consensus so I can propose the coded rule.

**Comment by Pandapip1** [comment]
I'd say that for now, it should be manually merged and always fail.
