### ISSUE TITLE
Bot should follow normal rules for changing files in assets directory.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereum/EIP-Bot#92]
If an author is making changes to the assets associated with a non-final/non-stagnant/non-withdrawn PR, those changes should auto-merge without editor intervention.

See https://github.com/ethereum/EIPs/pull/5148 for an example.

**Comment by Pandapip1** [comment]
Duplicate / Superseded by https://github.com/ethereum/EIP-Bot/issues/95
