### ISSUE TITLE
EIP Bot should error if a file contains an SPDX identifier other than CC0

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/EIP-Bot#96]
This would help avoid things like https://github.com/ethereum/EIPs/blob/master/assets/eip-4400/contracts/ERC721Consumable.sol having the wrong license.

**Comment by JEAlfonsoP** [comment]
Please could you check PR 87. I think that resolves this issue either.

**Comment by MicahZoltu** [comment]
#87

**Comment by MicahZoltu** [comment]
Addressed by EIPW now.

**Comment by SamWilsn** [comment]
It isn't (see ethereum/eipw#11), and _only_ checking the EIP itself is on the roadmap. I don't have any plans to scan Solidity files (or `package.json`, or anything other package manager's files.)

**Comment by Pandapip1** [comment]
> I don't have any plans to scan Solidity files (or package.json, or anything other package manager's files.)
Uh, why not?

**Comment by SamWilsn** [comment]
> Uh, why not?

I feel like scanning projects for licenses is incredibly hard, and I'd rather not create a lint that gives an over-exaggerated sense of safety.

**Comment by Pandapip1** [comment]
I can write those lints if you want. I'd have to learn rust first, but it can't be too hard... right?

**Comment by SamWilsn** [comment]
Rust is fun! Totally open to a PR, but keep my concern in mind.

**Comment by Pandapip1** [comment]
Did one better: https://github.com/ethereum/EIPs/pull/5379

**Comment by MicahZoltu** [comment]
Re-opening this until this gets implemented *somewhere*, or an issue to track the problem is created somewhere.

**Comment by MicahZoltu** [comment]
Branch protection rule updated.

**Comment by Pandapip1** [comment]
Tracked in https://github.com/ethereum/EIPs/pull/5379
